### ISSUE TITLE
[Rejected][System Test] Infinite Loop on incorrect input to save new Employee - Possible due to IDE

### ISSUE THREAD

**Issue by PhilipWoulfe** [CrazeeIvan/ICT_ProceduralProgramming#1]
Bug Report
Infinite Loop on incorrect input to save new Employee

Submitter
Philip Woulfe

Date Seen
2016-05-12 18:38

Versions
Windows 10
Assignment v0.7
Run on Visual Studio Community
Old POS

Bug Description
An infinite loop is started when attempting to add a new employee. The scanf in the add_new_employee method doesn't seem to be stopping for input. Issue may be due to my use of Visual Studio as an IDE.

(What are yo using to compile and run this? VS is throwing errors for option and submenu not being initialised in ass.c. I had to assign them null. VS doesn't seem to like to play nice with other programs.)

Severity
Catastrophic (Do we have a higher priority than this? Task 2: Create higher severity status)

Steps to Reproduce
1. Run program
2. Select Employees menu option >> Press enter
3. Select Add Employees menu option >> Press enter
4. Enter first name of employee >> Enter
5. Enter Second name of employee >> Enter
6. Enter Department (NB see bug #122678 - No validation on department input) >> Enter
7. Enter Pay Rate >> (NB see bug # 122679 - No validation on pay rate input_) >> Enter

Actual Behavior
Infinite loop - 
    Invalid input, please try again.
            Save?
            1. Yes/2. No

![image](https://cloud.githubusercontent.com/assets/8867626/15224986/19722b52-1874-11e6-8cd0-eebea79151ad.png)

Expected Behavior
Not that ^^

Troubleshooting/Testing Steps Attempted
I figured writing a smart arse bug report would be the best thing

Workaround
If you found a way to make the program work in spite of the bug, describe how you did it here.
![image](https://cloud.githubusercontent.com/assets/8867626/15225013/3e949d3e-1874-11e6-903d-153f9595cc4b.png)

**Comment by CrazeeIvan** [comment]
What version are you using? I tried to reproduce this bug but haven't been able to... there is another known bug with an infinite loop, but this one is new to me. I tried following your reproduction steps but seemed there was something more missing. After I enter the payrate, if I press 1; it stores the data, if I press 2, it exits and returns to the menu (there should be a confirmation dialogue there at some point)

Also, nice bug report!
I'm using GCC to compile, and Atom as my IDE/Text editor.

**Comment by PhilipWoulfe** [comment]
**Ticket:** Rejected
**Reason:** Raised in error
**Comment:** Error due to testing department using an unsupported compiler. Tester has been administered 50 lashes

Yeah, just used GCC to compile and it's working like it should. 
When I was running it in Visual Studio, it wasn't stopping the program at the scanf, so it hit the loop with confirm == 0 and looped constantly after that, which is the actual infinite loop you mentioned I take it? When it doesn't get a value of 1 or 2. That's the defect I thought I was writing when I started.

I suspect I'm going to regret using VS. I had trouble just transferring my own project from VS Community to VS Community 2015 and then I had more trouble transferring it back. 

App's looking good. I hadn't thought of using headers to organise the code like that. I'm surprised by how similar to an OOP layout a lot of this is... apart from pointers, fuck pointers. Every time I think I understand pointers, it turns out I don't.
